### ISSUE TITLE
Problem with command make train-repd

### ISSUE THREAD

**Issue by LuisQ95** [RasaHQ/conversational-ai-workshop-18#13]
Hi, i have a problem with this command 

python -m rasa_core.train -s data/core/ -d domain.yml -o models/dialogue -c redp.yml --augmentation_factor 0

![image](https://user-images.githubusercontent.com/40223102/49660254-1e555980-fa14-11e8-96f3-bcd825ba0f67.png)

I have install requeriments.txt correctly but i still have the same problem.

**Comment by LuisQ95** [comment]
Now, i have other problem

![image](https://user-images.githubusercontent.com/40223102/49660992-f666f580-fa15-11e8-8fc0-6099346c28ad.png)

my rasa_core is 0.12.3 rasa_core_sdk 0.12.1 and rasa_nlu 0.13.7

OS Windows 7 Service Pack 1

**Comment by akelad** [comment]
Hi @LuisQ95 i believe all this should be fixed now, sorry for the late response
