### ISSUE TITLE
Training Errors

### ISSUE THREAD

**Issue by ksurya** [RasaHQ/conversational-ai-workshop-18#15]
<img width="906" alt="screen shot 2018-12-14 at 5 53 26 pm" src="https://user-images.githubusercontent.com/932927/50034086-36efe180-ffc9-11e8-822e-7a2c84f9aede.png">

**Comment by akelad** [comment]
should be fixed now, the requirements weren't up to date

**Comment by HotSwap** [comment]
Just opened a new ticket: https://github.com/RasaHQ/conversational-ai-workshop-18/issues/16
