### ISSUE TITLE
Problem running model

### ISSUE THREAD

**Issue by HotSwap** [RasaHQ/conversational-ai-workshop-18#16]
Hi. Thanks for the update. Few things:

1.) The README file is still referring to "make train-core", which is not specified in the make file.
2.) When I run the "train-redp" command (python -m rasa_core.train -s data/core/ -d domain.yml -o models/dialogue -c redp.yml --augmentation 0). I get the following output:

![image](https://user-images.githubusercontent.com/503946/50285070-f1ad3300-0452-11e9-9ad4-1ad7b75aa354.png)

And then when I try to run "run-core" (python -m rasa_core.run --core models/dialogue --endpoints endpoints.yml). I get the following:

![image](https://user-images.githubusercontent.com/503946/50285087-fd98f500-0452-11e9-9a74-cd57172630c9.png)

I am using Python 3.6.7 and Ubuntu 18.10 x64. Any guidance on how to get this model running would be greatly appreciated. We are very excited to try this. Thanks.

**Comment by texpomru13** [comment]
@HotSwap hi!
did you deal with this problem?

**Comment by HotSwap** [comment]
Hi @texpomru13 Not yet, but I am still very interested to get this running so that I can try out these new features. Are you having a similar issue?

**Comment by akelad** [comment]
Sorry, kind of missed this issue. I'll take a look at what's going on.

**Comment by akelad** [comment]
Ok I've just fixed it, the yaml files were misdefined so the model wasn't training at all. Also I've updated the README, so everything should be fine now. Let me know if you encounter any other issues though

**Comment by HotSwap** [comment]
Thanks! I'm going to give this another go now. Will let you know if I hit any other issues.
