### ISSUE TITLE
Stories data simultation 

### ISSUE THREAD

**Issue by Sekhar-jami** [RasaHQ/conversational-ai-workshop-18#17]
The paper mentions that the stories data was generated using a simulated user to interact with the bootstrapped policy. Could you explain how to do that, or is it possible for us to get a look at that code?

**Comment by akelad** [comment]
@Sekhar-jami there's some code on a branch here which you can take a look at: https://github.com/RasaHQ/conversational-ai-workshop-18/blob/sim_user/sim_user.py
Keep in mind it may be a bit outdated as it's close to one year old now :)

**Comment by nghidinhit** [comment]
I cannot find models/dialogue_all when run sim_user.py
